AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS SDK Layer

Resources:
  SDKlayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: python-jwt
      Description: Python JWT package.
      ContentUri: './python'
      CompatibleRuntimes:
        - python3.9
      CompatibleArchitectures:
        - x86_64
      LicenseInfo: 'Available under the MIT-0 license.'
    Metadata:
      BuildMethod: makefile